### PR TITLE
fix: replace forEach to fix race condition

### LINKED ISSUE #121: Refactor seed data files to not use `forEach`
# Requirements

- [ ] no `forEach` while loading the db
- [ ] files to modify: `devSetup.ts` and `seed.ts`

There was a race condition and we were getting indeterminate tests

# Dependencies

- None (Add any issue dependencies here)

### PR DESCRIPTION
**Pull request by theyokohamalife**
Resolves #121 

# What changed
Changes the `forEach` in the seed functions to for loops, because we discovered a race condition in #116.

# Testing instructions
1. Run `docker compose up`
2. Run `yarn prisma studio`
3. Confirm that the seeds in Prisma Studio match those found in `specialties.csv` and `spokenLanguages.csv`

### CODE REVIEW

File: prisma/seed.ts [hunk 1]
```diff
@@ -15,23 +15,24 @@ async function seedSpokenLanguages(verbose = false) {
...
-                nameJa: language[jaCol],
-                nameNative: language[nativeCol]
+                iso639_3: spokenLanguage[iso639Col],
+                nameEn: spokenLanguage[enCol],
+                nameJa: spokenLanguage[jaCol],
+                nameNative: spokenLanguage[nativeCol]
             }
         })
-
+
```
Comment (theyokohamalife) [inline prisma/seed.ts:30]: I formatted the document with eslint and it put this space here 🧐

**Review by ann-kilzer — APPROVED** [review]
Thanks
