### PR TITLE
Fix CI/CD linting

### LINKED ISSUE #70: Get reviewdog to match local linting
See LaShawn's comment here

       @ann-kilzer eslint doesn't like for imports to have file extensions. Could this be disabled in reviewdog?

Screen Shot 2023-01-01 at 2 06 52 AM

_Originally posted by @theyokohamalife in https://github.com/ourjapanlife/findadoc-server/pull/62#discussion_r1059663958_

### PR DESCRIPTION
**Pull request by ann-kilzer**
Resolves #70 

# What changed

Fix the linting challenges in CI/CD

# Testing instructions

edit a file with some typescript and hope the dog chills out

### CODE REVIEW

**Comment by ann-kilzer** [comment]
I was investigating this thread: https://stackoverflow.com/questions/59265981/typescript-eslint-missing-file-extension-ts-import-extensions but not having much luck :/

File: prisma/seed.ts [hunk 1]
```diff
@@ -3,7 +3,7 @@
 // Seed data for the database
```
Comment (ann-kilzer) [inline prisma/seed.ts:3]: I was trying to see if Reviewdog would do something here by editing the import line 🤔

**Review by theyokohamalife — APPROVED** [review]
It looks like it works, but time will tell if the dog runs amok again 🤣
