### PR TITLE
fix: add conditionals to allow updating specific fields

### LINKED ISSUE #644: Fix validations errors when updating a healthcare professional
# Summary

Currently, updating a healthcare professional requires all fields to be provided. Attempting to update only specific fields, such as the name, results in a validation error stating that required fields are missing.

# Requirements

- [ ] Update validation logic to apply checks only to fields included in the update request.

# Dependencies

- None (Add any issue dependencies here)

### PR DESCRIPTION
**Pull request by Anissa3005**
Resolves #644

Previously, updating a healthcare professional required all fields to be provided. If any fields were missing, it caused validation errors.

This PR adds conditionals to the validation logic, allowing updates to one or more specific fields. For example, you can now update only the name field without providing other fields.

# What changed

1. Add conditionals to the `validateUpdateProfessionalInput` function.

# Testing instructions

### CODE REVIEW

File: src/services/healthcareProfessionalService.ts [hunk 1]
```diff
@@ -681,8 +681,18 @@ function validateUpdateProfessionalInput(input: Partial<gqlTypes.UpdateHealthcar
...
+            field: 'input',
+            errorCode: ErrorCode.MISSING_INPUT,
+            httpStatus: 400
+        })
+        return validationResults
+    }
+
     //business rule: at least one facility id is required
-    if (!input.facilityIds || input.facilityIds.length < 1) {
+    if (input.facilityIds && input.facilityIds.length < 1) {
```
Comment (ermish) [inline src/services/healthcareProfessionalService.ts:695]: I don't think this logic really makes sense anymore actually since the facilityIds here are facilityId updates. 
I think the logic here would be to check if the updates are making the facilityId count less than 1.

**Review by ermish — CHANGES_REQUESTED** [review]
nice! I added one comment. Feel free to slack me if it's confusing

**Review by ermish — APPROVED** [review]
ship it! :shipit:
